name: Documentation
description: Report an issue related to the SciPy documentation.
title: "DOC: "
labels: [Documentation]

body:
- type: textarea
  attributes: 
    label: "Issue with current documentation:"
    description: >
      Please make sure to leave a reference to the document/code you're
      referring to. You can also check the development version of the
      documentation and see if this issue has already been addressed at
      https://https://scipy.github.io/devdocs/.

- type: textarea
  attributes:
    label: "Idea or request for content:"
    description: >
      Please describe as clearly as possible what topics you think are missing
      from the current documentation.

- type: textarea
  attributes:
    label: Additional context (e.g. screenshots, GIFs)
